src/Entity/Budynki.php
<?php

namespace App\Entity;

use App\Repository\BudynkiRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=BudynkiRepository::class)
 */
class Budynki
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $Adres;

    /**
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $Typ;

    /**
     * @ORM\ManyToOne(targetEntity="Spoldzielnie")
     * @ORM\JoinColumn(name="Nazwa", referencedColumnName="nazwa")
     */
    private $Nazwa;

    public function __toString(){
        return $this->Adres;
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addConstraint(new UniqueEntity(['fields' => 'Adres', 'message' => 'Istnieje już budynek pod takim adresem.']));

        $metadata->addPropertyConstraint('Adres', new Assert\NotNull(['message' => 'Adres nie może być pusty.']));
        $metadata->addPropertyConstraint('Adres', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długi adres budynku.']));
        
        $metadata->addPropertyConstraint('Typ', new Assert\NotNull(['message' => 'Typ budynku nie może być pusty.']));
        $metadata->addPropertyConstraint('Typ', new Assert\Regex(['pattern'=> '/^[^0-9;,\'\.]+$/', 'message' => 'Typ budynku zawiera niepoprawne znaki.']));
        $metadata->addPropertyConstraint('Typ', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długa nazwa typu budynku.']));
        
        $metadata->addPropertyConstraint('Nazwa', new Assert\NotNull(['message' => 'Nazwa społdzielni nie może być pusta.']));
        $metadata->addPropertyConstraint('Nazwa', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długa nazwa spółdzielni.']));
    }

    public function getAdres()
    {
        return $this->Adres;
    }

    public function setAdres($Adres)
    {
        $this->Adres = $Adres;
    }

    public function getTyp()
    {
        return $this->Typ;
    }

    public function setTyp($Typ)
    {
        $this->Typ = $Typ;
    }

    public function getNazwa()
    {
        return $this->Nazwa;
    }

    public function setNazwa($Nazwa)
    {
        $this->Nazwa = $Nazwa;
    }
}

src/Entity/ObiektyNajmu.php
<?php

namespace App\Entity;

use App\Repository\ObiektyNajmuRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ObiektyNajmuRepository::class)
 * @ORM\Table(indexes={@ORM\Index(name="Adres_idx", columns={"Adres"})})
 */
class ObiektyNajmu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $Mieszkanie;

    /**
     * @ORM\Column(type="decimal", precision=3, nullable=false)
     */
    private $Nr_mieszkania;

    /**
     * @ORM\ManyToOne(targetEntity="Budynki")
     * @ORM\JoinColumn(name="Adres", referencedColumnName="adres")
     */
    private $Adres;

    /**
     * @ORM\Column(type="decimal", precision=7, scale=2, nullable=false)
     */
    private $Powierzchnia;

    /**
     * @ORM\Column(type="string", length=100, nullable=false, columnDefinition="ENUM('Mieszkanie', 'Pokój')")
     */
    private $Rodzaj_obiektu;

    /**
     * @ORM\Column(type="decimal", precision=2, nullable=true)
     */
    private $Liczba_pokoi;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Typ_mieszkania;

    /**
     * @ORM\Column(type="decimal", precision=3, nullable=true)
     */
    private $Nr_pokoju;

    public function __toString()
    {
        return $this->Adres . ' / ' . $this->Nr_mieszkania;
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addConstraint(new UniqueEntity(['fields' => ['Nr_mieszkania', 'Adres'], 'message' => 'Istnieje już taki obiekt pod danym adresem.']));

        $metadata->addPropertyConstraint('Nr_mieszkania', new Assert\NotNull(['message' => 'Numer mieszkania nie może być pusty.']));
        $metadata->addPropertyConstraint('Nr_mieszkania', new Assert\Type(['type' => 'numeric', 'message' => 'Numer mieszkania powinien być typu numerycznego.']));
        $metadata->addPropertyConstraint('Nr_mieszkania', new Assert\Regex(['pattern' => '/^[0-9]{1,3}$/', 'message' => 'Nieprawidłowy format numeru mieszkania.']));
        $metadata->addPropertyConstraint('Nr_mieszkania', new Assert\GreaterThanOrEqual(['value' => 1, 'message' => 'Numer mieszkania nie powinien być mniejszy niż 1.']));
        $metadata->addPropertyConstraint('Nr_mieszkania', new Assert\LessThanOrEqual(['value' => 999, 'message' => 'Numer mieszkania nie powinien być większy niż 999.']));
        
        $metadata->addPropertyConstraint('Adres', new Assert\NotNull(['message' => 'Adres obiektu najmu nie powinien być pusty.']));
        $metadata->addPropertyConstraint('Adres', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długi adres obiektu najmu.']));
        
        $metadata->addPropertyConstraint('Powierzchnia', new Assert\NotNull(['message' => 'Wartość powierzchni nie powinna być pusta.']));
        $metadata->addPropertyConstraint('Powierzchnia', new Assert\Type(['type' => 'numeric', 'message' => 'Wartość powierzchni powinna być typu numerycznego.']));
        $metadata->addPropertyConstraint('Powierzchnia', new Assert\GreaterThan(['value' => 0.00, 'message' => 'Powierzchna nie powinna być mniejsza niż 0.']));
        $metadata->addPropertyConstraint('Powierzchnia', new Assert\LessThanOrEqual(['value' => 9999999.99, 'message' => 'Powierzchnia nie powinna być większa niż 9999999.99.']));

        $metadata->addPropertyConstraint('Rodzaj_obiektu', new Assert\NotNull(['message' => 'Rodzaj obiektu nie powinien być pusty.']));
        $metadata->addPropertyConstraint('Rodzaj_obiektu', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długa nazwa rodzaju obiektu.']));

        $metadata->addPropertyConstraint('Liczba_pokoi', new Assert\Type(['type' => 'numeric', 'message' => 'Liczba pokoi powinna być typu numerycznego.']));
        $metadata->addPropertyConstraint('Liczba_pokoi', new Assert\Regex(['pattern' => '/^[0-9]{1,2}$/', 'message' => 'Nieprawidłowy format liczby pokoi.']));
        $metadata->addPropertyConstraint('Liczba_pokoi', new Assert\GreaterThanOrEqual(['value' => 1, 'message' => 'Liczba pokoi powinna być nie mniejsza niz 1.']));
        $metadata->addPropertyConstraint('Liczba_pokoi', new Assert\LessThanOrEqual(['value' => 99, 'message' => 'Liczba pokoi powinna być nie większa niz 99.']));
        $metadata->addPropertyConstraint('Liczba_pokoi', new Assert\Expression(['expression' => '(this.getRodzajObiektu() == "Mieszkanie" and this.getLiczbaPokoi() != null) or (this.getRodzajObiektu() != "Mieszkanie" and this.getLiczbaPokoi() == null)', 'message' => 'Wybrano niewłaściwą konfigurację lub wartość liczby pokoi jest pusta.']));

        $metadata->addPropertyConstraint('Typ_mieszkania', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długa nazwa typu mieszkania.']));
        $metadata->addPropertyConstraint('Typ_mieszkania', new Assert\Expression(['expression' => '(this.getRodzajObiektu() == "Mieszkanie" and this.getTypMieszkania() != null) or (this.getRodzajObiektu() != "Mieszkanie" and this.getTypMieszkania() == null)', 'message' => 'Wybrano niewłaściwą konfigurację lub wartość typu mieszkania jest pusta.']));
        $metadata->addPropertyConstraint('Typ_mieszkania', new Assert\Regex(['pattern' => '/^[^0-9,;\'\"\.]+$/', 'message' => 'Nieprawidłowy format typu mieszkania.']));

        $metadata->addPropertyConstraint('Nr_pokoju', new Assert\Type(['type' => 'numeric', 'message' => 'Numer pokoju powinien być typu numerycznego.']));
        $metadata->addPropertyConstraint('Nr_pokoju', new Assert\Regex(['pattern' => '/^[0-9]{1,3}$/', 'message' => 'Nieprawidłowy format numeru pokoju.']));
        $metadata->addPropertyConstraint('Nr_pokoju', new Assert\GreaterThanOrEqual(['value' => 1, 'message' => 'Numer pokoju powinien być nie mniejszy niż 1.']));
        $metadata->addPropertyConstraint('Nr_pokoju', new Assert\LessThanOrEqual(['value' => 999, 'message' => 'Numer pokoju powinien być nie większy niż 999.']));
        $metadata->addPropertyConstraint('Nr_pokoju', new Assert\Expression(['expression' => '(this.getRodzajObiektu() == "Pokój" and this.getNrPokoju() != null) or (this.getRodzajObiektu() != "Pokój" and this.getNrPokoju() == null)', 'message' => 'Wybrano niewłaściwą konfigurację lub wartośc numeru pokoju jest pusta.']));
    }

    public function getMieszkanie()
    {
        return $this->Mieszkanie;
    }

    public function getNrMieszkania()
    {
        return $this->Nr_mieszkania;
    }

    public function setNrMieszkania($Nr_mieszkania)
    {
        $this->Nr_mieszkania = $Nr_mieszkania;
    }

    public function getAdres()
    {
        return $this->Adres;
    }

    public function setAdres($Adres)
    {
        $this->Adres = $Adres;
    }

    public function getPowierzchnia()
    {
        return $this->Powierzchnia;
    }

    public function setPowierzchnia($Powierzchnia)
    {
        $this->Powierzchnia = $Powierzchnia;
    }

    public function getRodzajObiektu()
    {
        return $this->Rodzaj_obiektu;
    }

    public function setRodzajObiektu($Rodzaj_obiektu)
    {
        $this->Rodzaj_obiektu = $Rodzaj_obiektu;
    }

    public function getLiczbaPokoi()
    {
        return $this->Liczba_pokoi;
    }

    public function setLiczbaPokoi($Liczba_pokoi)
    {
        $this->Liczba_pokoi = $Liczba_pokoi;
    }

    public function getTypMieszkania()
    {
        return $this->Typ_mieszkania;
    }

    public function setTypMieszkania($Typ_mieszkania)
    {
        $this->Typ_mieszkania = $Typ_mieszkania;
    }

    public function getNrPokoju()
    {
        return $this->Nr_pokoju;
    }

    public function setNrPokoju($Nr_pokoju)
    {
        $this->Nr_pokoju = $Nr_pokoju;
    }
}

src/Entity/Osoby.php
<?php

namespace App\Entity;

use App\Repository\OsobyRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=OsobyRepository::class)
 */
class Osoby
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=11)
     */
    private $PESEL;

    /**
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $Imie;

    /**
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $Nazwisko;

    /**
     * @ORM\Column(type="string", length=9, nullable=false)
     */
    private $Nr_telefonu;

    /**
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $Adres;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Email;

    public function __toString()
    {
        return $this->getImie().' '.$this->getNazwisko().', '.$this->getPESEL();
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addConstraint(new UniqueEntity(['fields' => 'PESEL', 'message' => 'Istnieje już osoba o takim PESELU.']));

        $metadata->addPropertyConstraint('PESEL', new Assert\NotNull(['message' => 'PESEL nie powinien być pusty.']));
        $metadata->addPropertyConstraint('PESEL', new Assert\Regex(['pattern' => '/^[0-9]{11}$/', 'message' => 'Nieprawidłowy format PESELu.']));
        
        $metadata->addPropertyConstraint('Imie', new Assert\NotNull(['message' => 'Imię nie powinno być puste.']));
        $metadata->addPropertyConstraint('Imie', new Assert\Regex(['pattern'=> '/^[^0-9;,\"\'\.]+$/', 'message' => 'Nieprawidłowy format imienia.']));
        $metadata->addPropertyConstraint('Imie', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długie imię.']));

        $metadata->addPropertyConstraint('Nazwisko', new Assert\NotNull(['message' => 'Nazwisko nie powinnno być puste.']));
        $metadata->addPropertyConstraint('Nazwisko', new Assert\Regex(['pattern'=> '/^[^0-9;,\"\'\.]+$/', 'message' => 'Nieprawidłowy format nazwiska.']));
        $metadata->addPropertyConstraint('Nazwisko', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długie nazwisko.']));
        
        $metadata->addPropertyConstraint('Nr_telefonu', new Assert\NotNull(['message' => 'Numer telefonu nie powinien być pusty.']));
        $metadata->addPropertyConstraint('Nr_telefonu', new Assert\Regex(['pattern' => '/^[0-9]{9}$/', 'message' => 'Nieprawidłowy format numeru telefonu.']));
        
        $metadata->addPropertyConstraint('Adres', new Assert\NotNull(['message' => 'Adres nie powinien być pusty.']));
        $metadata->addPropertyConstraint('Adres', new Assert\Regex(['pattern' => '/^[^0-9]+\ *[0-9]*\ *[0-9]+\/[0-9]+$/', 'message' => 'Nieprawidłowy format adresu.']));
        $metadata->addPropertyConstraint('Adres', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długi adres.']));

        $metadata->addPropertyConstraint('Email', new Assert\Regex(['pattern' => '/^[a-z]+@[a-z]+\.[a-z]+$/', 'message' => 'Nieprawidłowy format adresu email.']));
        $metadata->addPropertyConstraint('Email', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długa adres email.']));
    }

    public function getPESEL()
    {
        return $this->PESEL;
    }

    public function setPESEL($PESEL)
    {
        $this->PESEL = $PESEL;
    }

    public function getImie()
    {
        return $this->Imie;
    }

    public function setImie($Imie)
    {
        $this->Imie = $Imie;
    }

    public function getNazwisko()
    {
        return $this->Nazwisko;
    }

    public function setNazwisko($Nazwisko)
    {
        $this->Nazwisko = $Nazwisko;
    }

    public function getNrTelefonu()
    {
        return $this->Nr_telefonu;
    }

    public function setNrTelefonu($Nr_telefonu)
    {
        $this->Nr_telefonu = $Nr_telefonu;
    }

    public function getAdres()
    {
        return $this->Adres;
    }

    public function setAdres($Adres)
    {
        $this->Adres = $Adres;
    }

    public function getEmail()
    {
        return $this->Email;
    }

    public function setEmail($Email)
    {
        $this->Email = $Email;
    }
}

src/Entity/Zwierzeta.php
<?php

namespace App\Entity;

use App\Repository\ZwierzetaRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ZwierzetaRepository::class)
 */
class Zwierzeta
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $Gatunek;

    /**
     * @ORM\Column(type="decimal", precision=2, nullable=false)
     */
    private $Ilosc;

    /**
     * @ORM\ManyToOne(targetEntity="Umowy")
     * @ORM\JoinColumn(name="Id_umowy", referencedColumnName="id")
     */
    private $Id_umowy;

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addConstraint(new UniqueEntity(['fields' => ['Gatunek', 'Id_umowy'], 'message' => 'Istnieją już takie zwierzeta przypisane do konkretnej umowy.']));

        $metadata->addPropertyConstraint('Gatunek', new Assert\NotNull(['message' => 'Gatunek nie powinien być pusty.']));
        $metadata->addPropertyConstraint('Gatunek', new Assert\Length(['max' => 100, 'maxMessage' => 'Zbyt długa nazwa gatunku.']));
        $metadata->addPropertyConstraint('Gatunek', new Assert\Regex(['pattern' => '/^[^0-9,;\"\'\.]+$/', 'message' => 'Nieprawidłowy format gatunku.']));

        $metadata->addPropertyConstraint('Ilosc', new Assert\NotNull(['message' => 'Ilość zwierząt nie powinna być pusta.']));
        $metadata->addPropertyConstraint('Ilosc', new Assert\Type(['type' => 'numeric', 'message' => 'Ilość zwierząt powinna być typu numerycznego.']));
        $metadata->addPropertyConstraint('Ilosc', new Assert\Regex(['pattern' => '/^[0-9]{1,2}$/', 'message' => 'Nieprawidłowy format ilości zwierząt.']));
        $metadata->addPropertyConstraint('Ilosc', new Assert\GreaterThanOrEqual(['value' => 1, 'message' => 'Ilość zwierząt nie powinna być mniejsza niż 1.']));
        $metadata->addPropertyConstraint('Ilosc', new Assert\LessThanOrEqual(['value' => 99, 'message' => 'Ilość zwierząt nie powinna być większa niż 99.']));

        $metadata->addPropertyConstraint('Id_umowy', new Assert\NotNull(['message' => 'ID umowy nie powinno być puste.']));
    }

    public function getId()
    {
        return $this->id;
    }

    public function getGatunek()
    {
        return $this->Gatunek;
    }

    public function setGatunek($Gatunek)
    {
        $this->Gatunek = $Gatunek;
    }

    public function getIlosc()
    {
        return $this->Ilosc;
    }

    public function setIlosc($Ilosc)
    {
        $this->Ilosc = $Ilosc;
    }

    public function getIdUmowy()
    {
        return $this->Id_umowy;
    }

    public function setIdUmowy($Id_umowy)
    {
        $this->Id_umowy = $Id_umowy;
    }
}

templates/find/findBudynki.html.twig
{% extends 'base.html.twig' %}

{% block title %}Budynki{% endblock %}

{% block body %}
    <div class="cointainer">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success alert-dismissible p-3 fade show" role="alert">
                        <h1></h1>
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}

                {% for message in app.flashes('error') %}
                    <div class="alert alert-danger alert-dismissible p-3 fade show" role="alert">
                        <h1></h1>
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
  </div>

   <div class="container">
        <div class="row">
            <div class="col">

                {{ form_start(form) }}
                {{ form_widget(form.Answer) }}
                {{ form_end(form) }}

            </div>
        </div>
    </div>

<div class="container">
<h1></h1>
                <div class="inline">
                <a href="/sbd-projekt/public/NowyBudynek" class="btn btn-primary btn-lg" role="button">Dodaj</a>
                <a href="javascript:history.back()" class="btn btn-primary btn-lg">Cofnij</a>

                {% if budynki %}
                    <table id="umowy" class="table table-striped">
                    <thead>
                        <tr>
                            <th>Budynek</th>
                            <th>Adres</th>
                            <th>Opcje</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for budynek in budynki %}
                            <tr>
                                <td>{{ budynek.typ }}</td>
                                <td>{{ budynek.adres }}</td>
                                <td>
                                    <a href="/sbd-projekt/public/WyswietlBudynki/{{ budynek.adres }}" class="btn btn-dark">Szczegóły</a>
                                    <a href="/sbd-projekt/public/WyswietlBudynki/edit/{{ budynek.adres }}" class="btn btn-secondary">Edytuj</a>
                                    <a href="/sbd-projekt/public/WyswietlBudynki/delete/{{ budynek.adres }}" class="btn btn-danger">Usuń</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                {% else %}
                    <p>Brak budynków do wyświetlenia</p>
                {% endif %}
           </div>
{% endblock %}

templates/find/findObiektyNajmu.html.twig
{% extends 'base.html.twig' %}

{% block title %}Umowy{% endblock %}

{% block body %}
    <div class="cointainer">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success alert-dismissible p-3 fade show" role="alert">
                        <h1></h1>
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}

                {% for message in app.flashes('error') %}
                    <div class="alert alert-danger alert-dismissible p-3 fade show" role="alert">
                        <h1></h1>
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
  </div>

   <div class="container">
        <div class="row">
            <div class="col">

                {{ form_start(form) }}
                {{ form_widget(form.Answer) }}
                {{ form_end(form) }}

            </div>
        </div>
    </div>

<div class="container">
<h1></h1>
                <a href="/sbd-projekt/public/NowyObiektNajmu" class="btn btn-primary btn-lg" role="button">Dodaj</a>
                <a href="javascript:history.back()" class="btn btn-primary btn-lg">Cofnij</a>

                {% if obiektynajmu %}
                    <table id="umowy" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Obiekt Najmu</th>
                                <th>Ulica</th>
                                <th>Numer<th>
                                <th>Opcje</th>
                            </tr>
                        </thead>
                    <tbody>
                    {% for obiekt in obiektynajmu %}
                        <tr>
                            <td>{{ obiekt.rodzaj_obiektu }}</td>
                            <td>{{ obiekt.Adres }}</td>
                            <td>{{ obiekt.nr_mieszkania }}</td>
                            <td>
                                <a href="/sbd-projekt/public/WyswietlObiektyNajmu/{{ obiekt.mieszkanie }}" class="btn btn-dark">Szczegóły</a>
                                <a href="/sbd-projekt/public/WyswietlObiektyNajmu/edit/{{ obiekt.mieszkanie }}" class="btn btn-secondary">Edytuj</a>
                                <a href="/sbd-projekt/public/WyswietlObiektyNajmu/delete/{{ obiekt.mieszkanie }}" class="btn btn-danger">Usuń</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                {% else %}
                    <p>Brak umów do wyświetlenia</p>
                {% endif %}
            </div>
{% endblock %}

templates/find/findOsoby.html.twig
{% extends 'base.html.twig' %}

{% block title %}Osoby{% endblock %}

{% block body %}
    <div class="cointainer">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success alert-dismissible p-3 fade show" role="alert">
                        <h1></h1>
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}

                {% for message in app.flashes('error') %}
                    <div class="alert alert-danger alert-dismissible p-3 fade show" role="alert">
                        <h1></h1>
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
  </div>

   <div class="container">
        <div class="row">
            <div class="col">

                {{ form_start(form) }}
                {{ form_widget(form.Answer) }}
                {{ form_end(form) }}

            </div>
        </div>
    </div>

<div class="container">
<h1></h1>
                <a href="/sbd-projekt/public/NowaOsoba" class="btn btn-primary btn-lg" role="button">Dodaj</a>
                <a href="javascript:history.back()" class="btn btn-primary btn-lg">Cofnij</a>

                {% if osoby %}
                    <table id="umowy" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Imię</th>
                                <th>Nazwisko</th>
                                <th>PESEL</th>
                                <th>Opcje</th>
                            </tr>
                        </thead>
                    <tbody>
                    {% for osoba in osoby %}
                        <tr>
                            <td>{{ osoba.imie }}</td>
                            <td>{{ osoba.nazwisko }}</td>
                            <td>{{ osoba.pesel }}</td>
                            <td>
                                <a href="/sbd-projekt/public/WyswietlOsoby/{{ osoba.pesel }}" class="btn btn-dark">Szczegóły</a>
                                <a href="/sbd-projekt/public/WyswietlOsoby/edit/{{ osoba.pesel }}" class="btn btn-secondary">Edytuj</a>
                                <a href="/sbd-projekt/public/WyswietlOsoby/delete/{{ osoba.pesel }}" class="btn btn-danger">Usuń</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                {% else %}
                    <p>Brak osób do wyświetlenia</p>
                {% endif %}
            </div>
{% endblock %}